#include <QApplication>
#include <QGraphicsScene>
#include "Player.h"
#include <QGraphicsView>
#include "Game.h"

Game* game;

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);

    //TODO: seed number generated by time
    game = new Game(10000);
    game->show();

    return a.exec();
}
